name: Python CI/CD with Docker

on:
  push:
    branches:
      - main  # Trigger workflow only on push events to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Use Python 3.11

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password from secrets

      # Step 5: Build the Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest .

      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest
